### ISSUE TITLE
ML_essentials_Two supervised learner models?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#10]
We have built and tested two supervised learner models - M1 and M2. We compare the test set accuracy of the models using the classical hypothesis testing paradigm using a 95% confidence setting. The computed value of P is 2.53. What can we say about this result?

Select one:

- [x] A. The models differ significantly in their performance
- [ ] B. Model M1 performs significantly better than M2
- [ ] C. Model M2 performs significantly better than M1
- [ ] D. Both models perform at the same level of accuracy

**Comment by izxi** [comment]
[what a p-Value](http://www.dummies.com/education/math/statistics/what-a-p-value-tells-you-about-statistical-data/)

**Comment by johnnieng** [comment]
A. The models differ significantly in their performance *
