### ISSUE TITLE
Which of the following best describes the process of data mining?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#12]
Which of the following best describes the process of data mining?

Select one:

- [ ]  A. Representing data
- [ ]  B. Deducing relationship in data
- [x]  C. Identifying patterns in data
- [ ]  D. Simulating trends in data

**Comment by izxi** [comment]
**Data Mining**: Concepts and Techniques provides the concepts and techniques in processing gathered data or information, which will be used in various applications. Specifically, it explains data mining and the tools used in discovering knowledge from the collected data.

**Comment by johnnieng** [comment]
C. Identifying patterns in data *
