### ISSUE TITLE
Evaluate the relationship between a categorical variable and a numerical variable?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#17]
Which of the following statistical techniques can be used to evaluate the relationship between a categorical variable and a numerical variable?

Select one:

- [ ] - A. ANOVA
- [ ] - B. Pearson's Correlation coefficient
- [x] - C. Chi-squared
- [ ] - D. Root mean squared error

**Comment by izxi** [comment]
[Analysis of Variance](http://onlinestatbook.com/2/analysis_of_variance/intro.html) (ANOVA) is a statistical method used to test differences between two or more means. It may seem odd that the technique is called "Analysis of Variance" rather than "Analysis of Means." As you will see, the name is appropriate because inferences about means are made by analyzing variance.

**Comment by izxi** [comment]
The [Pearson correlation coefficient](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.pearsonr.html) measures the linear relationship between two datasets. Strictly speaking, Pearson’s correlation requires that each dataset be normally distributed. Like other correlation coefficients, this one varies between -1 and +1 with 0 implying no correlation. Correlations of -1 or +1 imply an exact linear relationship. Positive correlations imply that as x increases, so does y. Negative correlations imply that as x increases, y decreases.

**Comment by izxi** [comment]
The root-mean-square deviation (RMSD) or **root-mean-square error** (RMSE) (or sometimes root-mean-squared error) is a frequently used measure of the differences between values (sample and population values) predicted by a model or an estimator and the values actually observed.

**Comment by izxi** [comment]
There are basically two types of random variables and they yield two types of data: numerical and categorical. A [chi square](http://math.hws.edu/javamath/ryan/ChiSquare.html) (X2) statistic is used to investigate whether distributions of categorical variables differ from one another. Basically categorical variable yield data in the categories and numerical variables yield data in numerical form. Responses to such questions as "What is your major?" or Do you own a car?" are categorical because they yield data such as "biology" or "no." In contrast, responses to such questions as "How tall are you?" or "What is your G.P.A.?" are numerical. Numerical data can be either discrete or continuous. The table below may help you see the differences between these two variables.

**Comment by johnnieng** [comment]
A. ANOVA *

**Comment by om-ganesh** [comment]
@johnnieng do you have a reference to verify that the ANOVA is correct answer? I still think and go with @izxi (chi-squared)

**Comment by johnnieng** [comment]
> 
> 
> @johnnieng do you have a reference to verify that the ANOVA is correct answer? I still think and go with @izxi (chi-squared)

A chi-square test is used when you want to see if there is a relationship between two categorical variables.

**Comment by mebriki** [comment]
Answer: [ANOVA](https://www.researchgate.net/post/Which-statistical-test-will-be-the-most-appropriate-to-find-association-between-a-numerical-variable-and-a-categorical-variable)
Certainly, One-Way ANOVA or Independent t test. Chi square test is when both groups are categorical. Statisticians frown upon chopping numerical variables into groups.
Best,
- Alhaji

Another answer source: [ANOVA](https://www.quora.com/What-kind-of-test-should-I-use-to-test-the-correlation-between-categorical-and-numeric-variables)

![image](https://user-images.githubusercontent.com/35892987/139992758-ea66a2af-238e-4a67-80c0-3ba0743b6614.png)
