### ISSUE TITLE
Which of the following problems can be solved by machine learning methods?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#18]
Which of the following problems can be solved by machine learning methods?

Select one or more:

- [x] - A. Spam email detection
- [x] - B. Real time products recommendation according to user's click behaviors
- [x] - C. Clean data for analytics
- [x] - D. Predict next year's sale based on history data

**Comment by izxi** [comment]
[refer to](https://www.marutitech.com/problems-solved-machine-learning/)

**Comment by johnnieng** [comment]
Not A, B, C, D *

**Comment by mickyrocky** [comment]
Hi johnnieng 

ABCD is the right answer?

**Comment by mebriki** [comment]
Probably **_A, B, D_**
P. S. Cleaning Data is not machine learning, although it is an important step prior to any machine learning project.
