### ISSUE TITLE
Which of the following are TRUE? > Unsupervised Learning

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#20]
Which of the following are TRUE?

Select one or more:

- [ ] - A. Unsupervised learning is a type of machine learning without monitoring by a researcher
- [ ] - B. Unsupervised learning is a type of machine learning from data without a target variable
- [x] - C. Cluster analysis is a most commonly used unsurpervised learning method
- [x] - D. Unsupervised learning is a type of machine learning from data without labeled responses

**Comment by izxi** [comment]
[Unsupervised learning](https://ww2.mathworks.cn/discovery/unsupervised-learning.html)

Machine learning technique for finding hidden patterns or intrinsic structures in data
**Unsupervised learning** is a type of machine learning algorithm used to draw inferences from datasets consisting of input data without labeled responses.

The most common unsupervised learning method is **cluster analysis**, which is used for exploratory data analysis to find hidden patterns or grouping in data. The clusters are modeled using a measure of similarity which is defined upon metrics such as Euclidean or probabilistic distance.

Common clustering algorithms include:

- Hierarchical clustering: builds a multilevel hierarchy of clusters by creating a cluster tree
- k-Means clustering: partitions data into k distinct clusters based on distance to the centroid of a cluster
- Gaussian mixture models: models clusters as a mixture of multivariate normal density components
- Self-organizing maps: uses neural networks that learn the topology and distribution of the data
- Hidden Markov models: uses observed data to recover the sequence of states

Unsupervised learning methods are used in bioinformatics for sequence analysis and genetic clustering; in data mining for sequence and pattern mining; in medical imaging for image segmentation; and in computer vision for object recognition.

**Comment by johnnieng** [comment]
- B. Unsupervised learning is a type of machine learning from data without a target variable
- C. Cluster analysis is a most commonly used unsupervised learning method
- D. Unsupervised learning is a type of machine learning from data without labeled responses *

**Comment by mebriki** [comment]
**_Answer:_** B, C, D
[Unsupervised Learning](https://machinelearningmastery.com/types-of-learning-in-machine-learning/)
Compared to supervised learning, unsupervised learning **_operates upon only the input data without outputs or target variables_**. As such, unsupervised learning does not have a teacher correcting the model, as in the case of supervised learning.
