### ISSUE TITLE
Which of the following correlation coefficients represents the weakest correlation between two variables?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#22]
Which of the following correlation coefficients represents the weakest correlation between two variables?

Select one:

- [ ] - A. -0.10
- [ ] - B. -1.00
- [x] - C. 0.02
- [ ] - D. 0.10

**Comment by izxi** [comment]
- The strongest linear relationship is indicated by a correlation coefficient of -1 or1.

- The weakest linear relationship is indicated by a correlation coefficient equal to 0.

**Comment by johnnieng** [comment]
C. 0.02 *

**Comment by mebriki** [comment]
**_Answer:_** [C. 0.02](https://sphweb.bumc.bu.edu/otlt/MPH-Modules/PH717-QuantCore/PH717-Module9-Correlation-Regression/PH717-Module9-Correlation-Regression4.html)

![image](https://user-images.githubusercontent.com/35892987/140068747-d7659bab-7229-46e3-b6da-6f17bf82a72f.png)
