### ISSUE TITLE
Which of the following is TRUE?[Reinforcement learning]

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#23]
Which of the following is TRUE?

Select one:

- [x] - A. Reinforcement learning requires the agent to know the rewards for every action
- [ ] - B. Reinforcement learning works best with smaller state spaces
- [ ] - C. Reinforcement learning keeps a log of all individual actions taken by the agent
- [ ] - D. Reinforcement learning only models learning behavior in animals

**Comment by izxi** [comment]
[Reinforcement Learning](https://www.kdnuggets.com/2018/03/5-things-reinforcement-learning.html)(RL) is a type of machine learning technique that enables an agent to learn in an interactive environment by trial and error using feedback from its own actions and experiences.

**Comment by johnnieng** [comment]
B. Reinforcement learning works best with smaller state spaces *

**Comment by tyadav** [comment]
A. Reinforcement learning requires the agent to know the rewards for every action
