### ISSUE TITLE
Methods used to visualize data?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#27]
Which of the following are methods used to visualize data?

Select one or more:

- [x] A. Matrix diagram
- [x] B. Scatter plot
- [x] C. Histogram
- [x] D. Crosstabulation

**Comment by izxi** [comment]
[visualize data.pdf](https://pdfs.semanticscholar.org/4ff1/f2fff62e899f4b9f507b2eb4bb297b7febc2.pdf)

**Comment by johnnieng** [comment]
Wrong for A, B, C, D

**Comment by mickyrocky** [comment]
Hi johnnieng 
what "Wrong for A, B, C, D" means ?

Right answer is ABCD ?  Please assist

**Comment by johnnieng** [comment]
I guess the answer should be BC

**Comment by mickyrocky** [comment]
Thanks, I agree with you. I have few more questions, can you help?

**Comment by johnnieng** [comment]
> Thanks, I agree with you. I have few more questions, can you help?

Sure

**Comment by mickyrocky** [comment]
sorry, i missed your message. how do i contact you, can you message me your email id, please

**Comment by mebriki** [comment]
Most probably **_B, C_**
P. S. Matrix diagram and Crosstabulation are more analyzing tools (quantitatively and qualitatively)
