### ISSUE TITLE
What does supervised learning require that differentiates it from unsupervised clustering?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#29]
What does supervised learning require that differentiates it from unsupervised clustering?

Select one:

- [ ] A. At least one output attribute
- [ ] B. At least one input attribute
- [ ] C. Output attributes to be categorical
- [x] D. Input attributes to be categorical

**Comment by izxi** [comment]
[Differences Between Supervised Learning and Unsupervised Learning](http://www.differencebetween.net/technology/differences-between-supervised-learning-and-unsupervised-learning/)

**Comment by johnnieng** [comment]
A. At least one output attribute *
