### ISSUE TITLE
Which of the following are TRUE? > prescriptive,descriptive,diagnostic,predictive analytics

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#30]
Which of the following are TRUE?

Select one or more:

- [x] A. A prescriptive analytics answer might be: “What should we do?”
- [x] B. A descriptive analytics answer might be: “What has happened?”
- [ ] C. A diagnostic analytics answer might be: “What will happen?”
- [x] D. A predictive analytics answer might be: “What could happen?”

**Comment by izxi** [comment]
[Link](https://www.gartner.com/it-glossary/)

**Prescriptive Analytics** is a form of advanced analytics which examines data or content to answer the question “What should be done?” or “What can we do to make _______ happen?”, and is characterized by techniques such as graph analysis, simulation, complex event processing, neural networks, recommendation engines, heuristics, and machine learning.

**Descriptive Analytics** is the examination of data or content, usually manually performed, to answer the question “What happened?” (or What is happening?), characterized by traditional business intelligence (BI) and visualizations such as pie charts, bar charts, line graphs, tables, or generated narratives.

**Diagnostic Analytics** is a  form of advanced analytics which examines data or content to answer the question “Why did it happen?”, and is characterized by techniques such as drill-down, data discovery, data mining and correlations.

**Predictive analytics** describes any approach to data mining with four attributes:

1. An emphasis on prediction (rather than description, classification or clustering)
2. Rapid analysis measured in hours or days (rather than the stereotypical months of traditional data mining)
3. An emphasis on the business relevance of the resulting insights (no ivory tower analyses)
4. (increasingly) An emphasis on ease of use, thus making the tools accessible to business users.

**Comment by johnnieng** [comment]
A, B, D *
