### ISSUE TITLE
Which of the following is a key difference between Deep Learning and  Machine Learning?

### ISSUE THREAD

**Issue by rysbekova** [izxi/Learning#32]
- [ ] Machine Learning is based on assumptions while Deep Learning is not
- [ ] Machine Learning is used in a theoretical context and Deep Learning is its practical implementation
- [x] Deep Learning is a particular technique in Machine Learning
- [ ] The terms are interchangeable

**Comment by rysbekova** [comment]
https://blogs.nvidia.com/blog/2016/07/29/whats-difference-artificial-intelligence-machine-learning-deep-learning-ai/

**Comment by johnnieng** [comment]
Deep Learning is a particular technique in Machine Learning *
