### ISSUE TITLE
If you need to group points based on some feature, which machine learning method you should use?

### ISSUE THREAD

**Issue by rysbekova** [izxi/Learning#33]
- [ ] A. Naive Bayes Classifier
- [x] B. K-means
- [ ] C. Decision Tree
- [ ] D. Random Forests

**Comment by rysbekova** [comment]
https://www.coursera.org/lecture/machine-learning/k-means-algorithm-93VPG

**Comment by johnnieng** [comment]
B. K-means *

**Comment by om-ganesh** [comment]
@johnnieng I see lots of laugh emoji... Is that mean that is the correct answer? 
OR
It is not the correct answer and you are making laugh of it?

**Comment by johnnieng** [comment]
> 
> 
> @johnnieng I see lots of laugh emoji... Is that mean that is the correct answer?
> OR
> It is not the correct answer and you are making laugh of it?

Correct answer
