### ISSUE TITLE
Which tools offer Machine Learning capabilities?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#4]
Which tools offer Machine Learning capabilities?

Select one:

- [x]  A. R, Python, Spark, SPSS
- [ ]  B. R, SQL, Python, Spark
- [ ]  C. SQL, Python, Spark, SPSS
- [ ]  D. R, SQL, Spark, SPSS

**Comment by johnnieng** [comment]
A. R, Python, Spark, SPSS *
