### ISSUE TITLE
Data wrangling and data munging?

### ISSUE THREAD

**Issue by izxi** [izxi/Learning#7]
Which of the following are TRUE?

Select one or more:

- [x]  A. Data wrangling and data munging are ways of transforming raw data
- [x]  B. Data wrangling and data munging are ways of mapping raw data
- [ ]  C. Data wrangling and data munging are used to make analytics easy
- [ ]  D. Data wrangling and data munging are ways of merging two data sets

**Comment by izxi** [comment]
[link](https://www.slideshare.net/Dataversity/selfservice-data-analysis-data-wrangling-data-munging-and-data-modeling-how-do-they-fit-together)

**Comment by johnnieng** [comment]
Not A & B

**Comment by mebriki** [comment]
Probably **_A, B, C_**

[What is Data Wrangling?](https://www.inzata.com/data-wrangling-vs-data-cleaning-whats-the-difference/)
**_Data wrangling_**, also referred to as **_data munging_**, is the process of **_converting and mapping data from one raw format into another_**. The purpose of this is to prepare the data in a way that makes it a**_ccessible for effective use_** further down the line. Not all data is created equal, therefore it’s important to organize and transform your data in a way that can be easily accessed by others.

[Benefits of Data Wrangling](https://www.inzata.com/data-wrangling-vs-data-cleaning-whats-the-difference/)
Although data wrangling is an essential part of preparing your data for use, the process yields many benefits. Benefits include:
* Enhances ease of access to data
* **_Faster time to insights_**
* **_Improved efficiency_** when it comes to **_data-driven decision making_**
